### ISSUE TITLE
Flashing a device that only has a bootloader fails.

### ISSUE THREAD

**Issue by RudolphRrr** [jgressmann/supercan#1]
I built a new interface with an ATSAME51J18A-AU and flashed only the bootloader by debugger.
Using dfu-util 0.9 under windows with this command line:
dfu-util -d 1d50:5035,:5036 -R -D supercan.dfu

the result is:
Opening DFU capable USB device...
ID 1d50:5036
Run-time device DFU version 0101
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: error get_status

When I also flash the firmware by debugger though flashing by USB works:
Opening DFU capable USB device...
ID 1d50:5035
Run-time device DFU version 0101
Claiming USB DFU Runtime Interface...
Determining device status: state = appIDLE, status = 0
Device really in Runtime Mode, send DFU detach request...
error detaching
Resetting USB...
Opening DFU USB Device...
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 0101
Device returned transfer size 512
Copying data from PC to DFU device
Download        [=========================] 100%        27448 bytes
Download done.
state(7) = dfuMANIFEST, status(0) = No error condition is present
state(8) = dfuMANIFEST-WAIT-RESET, status(0) = No error condition is present
Done!
can't detach
Resetting USB to switch back to runtime mode

**Comment by jgressmann** [comment]
The 0.2.5 bootloader introduced a regression that prevent the bootloader from leaving the _DFU error_ state. Should be fixed on master.

**Comment by RudolphRrr** [comment]
Can confirm, works fine now with bootloader only.

**Comment by Matheus-Garbelini** [comment]
Hi @jgressmann just a quick question? I'm trying to find targets to test this tools.
Do you know of any commercial car model that use CAN FD to communicate with other ECUs?

**Comment by RudolphRrr** [comment]
We know a couple of car models that have CAN-FD busses but I am not sure we are at the liberty to discuss this.
Most likely any model that was introduced to the market in the last two years has at least one CAN-FD bus by now.

**Comment by Matheus-Garbelini** [comment]
@RudolphRrr mind you share some model privately via email?
I would just like one example as a reference because I'm not sure of any car model and consequently no motor ECU model.

**Comment by RudolphRrr** [comment]
I really can't.

But fishing the net with Google I found this article:
https://europe.autonews.com/automakers/vw-says-software-glitches-new-id3-ev-will-not-affect-sales-launch
"Whereas the Golf is only equipped with an evolutionary CAN FD electric-electronic (E/E) architecture,"

And as article is from january 2020 this probably refers to the Golf 8 model.
Also the VW Golf is based on a platform architecture, according to wiki "MQB evo".

So at least these listed under "MQB evo" should have a CAN-FD bus as well.
https://en.wikipedia.org/wiki/Volkswagen_Group_MQB_platform

While I would not go for the motor ECU as this is likely one of the most expensive ones I have no good tip for an alternative.
Well, whatever else is connected to the motor ECU on the same bus should do.

**Comment by Matheus-Garbelini** [comment]
Thanks @RudolphRrr I think your answer is what I was looking for.
Buying other ECUs from these models should give me a good test as you mention.
However, hopefully, they do not require any form of authentication or encryption when testing them in isolation.
Let's see!

**Comment by Matheus-Garbelini** [comment]
@RudolphRrr sorry to bother you again.
In regards to the specific behaviour of some car CAN Classic or FD ECU networks. 
Do you know if it's usual for the ECUs to limit the number of retries to avoid a retry loop due to repeatedly losing arbitration?

For example, is the situation below actually possible in commercial car CAN networks? (Infinite retries due to arbitration loss)
In this Figure, the "Injector" keeps sending valid frames with lower id than "Transmitter" ECU.
However, "Transmitter" ECU never gives up in trying to resend the interrupted frame.
![infinite_retries](https://user-images.githubusercontent.com/6465668/123838490-a25aee00-d93e-11eb-9d64-6b8c47765d51.png)

Is it specified somewhere a limit for automatic retries due to loss of arbitration?

Thanks in advance.

**Comment by RudolphRrr** [comment]
There are rules for everything but I am in the lucky position that I, for the most part, do not need to abide by them since I am in prototyping and not creating software that actually makes it into a production car.
These rules are in the car manufacturers specifications though and these are generally not public.

That said, for example the Bosch M-CAN module that is also found in the ATSAME51 I am using is by default shutting down the CAN pretty fast on its own whenever there is an issue.
While I always see to turn off such measures there should be hints in the reference manual regarding this behaviour.
And even when switching most of it off which leads to the behaviour in the trace when disconnecting the unit from the CAN, when there are errors from for example an invalid baud-rate for the bus or incorrectly configured timings for the baud-rate,
the module shuts down and needs to be reactivated.

**Comment by Matheus-Garbelini** [comment]
Thanks @RudolphRrr I'm asking this because it's perfectly understandable if the controller shuts down due to error frames since its transmitter error counter (TEC) will increase, leading to a bus-off state.

However, in the case that no error occurs, but frames are simply interrupted due to a higher priority one (arbitration loss), TEC will not increase, which leads to the question of whether the controller will eventually stop retransmitting.

**Comment by RudolphRrr** [comment]
I am not sure as this situation is rather unsual but I believe it should not stop retransmitting.

Controllers not be using a Bosch M-CAN would be dsPIC33CH256MP505 or Renesas RH850 F1Kx for example, NXPs S32K are also not using it I believe.
Annother example with Bosch M-CAN would be STM32H7, although not automotive.

**Comment by jgressmann** [comment]
@Matheus-Garbelini, @RudolphRrr  maybe you could exchange contact information so you can communicate more easily? Your conversation has nothing to do with the topic of this issue. Thanks.

**Comment by RudolphRrr** [comment]
There is a new feature on Github called "Discussions" which could be enabled.
But in general a public forum like the EEV-Blog forum would be a more suitable place: https://www.eevblog.com/forum/index.php
After all, this repository is for a well defined purpose. :-)

**Comment by jgressmann** [comment]
I wasn't aware of that, done. Thanks.
