### ISSUE TITLE
Support for CANBed M4?

### ISSUE THREAD

**Issue by marshallmassengill** [jgressmann/supercan#11]
Have been following for a while and just noticed SEEED is selling these: https://www.seeedstudio.com/Canbed-M4-p-4782.html

I suspect they could work with this without too much effort given they are SAME5 based.  Any chance support could be added?

Happy to try and help with this but not entirely sure where to start.  Looks like maybe the board support for tinyusb?  Thanks!

**Comment by marshallmassengill** [comment]
Yeah, I've got a debugger I can use for it.  It looks like the chip is the same as the Adafruit ItsyBitsy M4, which already has support in the tinyusb project.  I suspect that, combined with the Feather M4 CAN Express work you added would get the job done, maybe with some minor tweaks.  I was going to look at this weekend and see what I could manage to do.

**Comment by marshallmassengill** [comment]
No luck so far.  Ran into some weird issues that I think are from the specific includes for the feather M4.  Still working on this but going to take longer than I thought it would.

**Comment by jgressmann** [comment]
Supported as of [v1.0.18](https://github.com/jgressmann/supercan/releases/tag/v1.0.18)
