### ISSUE TITLE
Hi, is there any full project example for the source code?

### ISSUE THREAD

**Issue by zerotoney** [jgressmann/supercan#15]
![image](https://github.com/user-attachments/assets/3f60a0c2-021d-4e85-943a-281c2029730e)
From this folder, I can see the src. Are they for the STM firmware?

**Comment by jgressmann** [comment]
Does [this](https://github.com/jgressmann/supercan/discussions/14#discussioncomment-10911205) answer your question?

**Comment by zerotoney** [comment]
Thank you so much!!
