### ISSUE TITLE
Question about Portable Threads, circa 2006

### ISSUE THREAD

**Issue by hrieke** [jgressmann/supercan#4]
Hello Jean,

I have a question about some code of yours that is from your Potsdam university days, Portable Threads.
Sadly it appears that the majority of the code is lost to time (even the Wayback Machine / Internet Archive does not have a complete copy of the code). 
My question is about the initial license for the code:  The bits of code I have found show the GNU General Public License v2 or later, and then around 2006-ish you move the license to the BSD 3-clause.  Is this correct?

Could I ask you if you still have a copy, would it be possible to add it to Github?
Thank you!

Wayback Links:
https://web.archive.org/web/20100109133636/http://www.0x42.de/
https://web.archive.org/web/20090426042240/http://fara.cs.uni-potsdam.de:80/~jsg/nucleus
https://web.archive.org/web/*/http://fara.cs.uni-potsdam.de/~jsg/portablethreads/html/*
https://web.archive.org/web/20090511023841/http://fara.cs.uni-potsdam.de:80/~jsg/portablethreads/html/thread_8h-source.html

**Comment by jgressmann** [comment]
What a blast from the past :) I haven't thought of that code in years. I would have to dig around my old backups to see if it's still in there somewhere. 

What's your interest in the code?

**Comment by hrieke** [comment]
Doing a little research.

**Comment by jgressmann** [comment]
I found the old code. Looks like I was in the process of transitioning the license from GPL to BSD. By the looks of it, I missed a few headers. 

Since I left the university I abandoned the code. Its in pretty bad shape and I'd rather not publish it again.

**Comment by hrieke** [comment]
Thanks for confirming my guess there on the license change.

Stay safe
